const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

const UPDATE_SORT_METHOD = 'UPDATE_SORT_METHOD';
const UPDATE_SORT_ORDER = 'UPDATE_SORT_ORDER';

const SORT_DATA = 'SORT_DATA';

export {
  GET_DATA_REQUEST,
  GET_DATA_SUCCESS,
  GET_DATA_FAILURE,
  UPDATE_SORT_METHOD,
  UPDATE_SORT_ORDER,
  SORT_DATA,
};
